### ISSUE TITLE
Don't print `-Wunmapped-char` for any empty charmap

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1058]
Currently `-Wunmapped-char` complains if an unmapped character is used in a non-empty `main` charmap, or in a non-`main` charmap even if it's empty. But pokecrystal uses an empty charmap named `ascii` and it doesn't make sense to get this warning.

**Comment by aaaaaa123456789** [comment]
There are two scenarios here:
- A user doesn't want to use strings at all in some part of the program. They make a deliberately empty charmap and want to be warned on any string usage.
- A user wants to use raw UTF-8 in some part of the program. They make a separate charmap for that part.

The issue right now is that there's no way to make empty charmaps, so warnings are forced to guess. The real solution here is to add a way to create truly empty charmaps. Since that's a postponed feature, I'd recommend silencing the warning on any "unsure" cases like this one until that feature is added.

**Comment by ISSOtm** [comment]
I'd rather have two warning levels, `1` lax (`-Wall`) and `2` strict (`-Wextra`).

**Comment by ISSOtm** [comment]
Alternatively, have one or more "magic" names that will serve as the guess. The warning can suggest renaming the charmap to them if it's empty, to ease change. Possible names: `ascii`, `utf8`, `raw`?

**Comment by aaaaaa123456789** [comment]
I'd say that magic names are the worst solution to any problem. On the other hand, warning levels should be OK. Are you sure you'd want level 2 in `-Wextra`?

**Comment by ISSOtm** [comment]
> I'd say that magic names are the worst solution to any problem.

I don't think they're bad if they're explicitly specified as such, and the names themselves are fairly explicit (save maybe for `raw`). It's only a temporary solution until charmaps are improved, anyway.

> Are you sure you'd want level 2 in `-Wextra`?

I'd prefer it in `-Wall`, but I figured you'd oppose it.
