### ISSUE TITLE
Allow `rgbgfx -c embedded` to accept embedded palettes with extra unused colors

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1064]
Continuing discussion from #1062:

Currently `rgbgfx -c embedded` expects the PNG's indexed PLTE chunk to define exactly four colors. Some users may have PNGs with more than that (e.g. 256 colors), but only use colors 0-3. Arguably this should be a supported use case.

**Comment by ISSOtm** [comment]
No, because they may be expecting the extra colours to end up in the generated palette even if they aren't used. Ignoring extra colours if both `-n` and `-s` are specified, maybe.

**Comment by aaaaaa123456789** [comment]
How would that be a reasonable expectation when the palette is four colors?

**Comment by ISSOtm** [comment]
If it's four colours, then they would be used, and emitted in any order unless `-c` is passed. `-c` is the opt-in for "actually, I manipulate colours by index, so it's important that you respect this". Otherwise, they just want to display something, so they would just copy the binary palette data to CRAM.

Grayscale sorting makes more sense by default, since on DMG, palettes are a single byte—not something you'd want to `INCBIN`—so sorting in a way compatible with the common `$E4` palette is a good default.

**Comment by aaaaaa123456789** [comment]
I was talking about the GBC palette. How would it be reasonable to expect palette data to contain more than four colors (even if the image does) when the GBC palettes can only contain four colors?

**Comment by pinobatch** [comment]
Test case: `testcase2.png` has 8 colors and uses the first 4. `testcase3.png` has 4 colors. Converting them with `-c embedded` should produce the same character data.
![testcase2](https://user-images.githubusercontent.com/13617183/193050641-4da06f4a-717f-4238-834a-b52493b0aee6.png)
![testcase3](https://user-images.githubusercontent.com/13617183/193050642-f06f90e7-3d59-4401-a77c-635b91c4dbab.png)

**Comment by ISSOtm** [comment]
> I was talking about the GBC palette. How would it be reasonable to expect palette data to contain more than four colors (even if the image does) when the GBC palettes can only contain four colors?

If it contains 8, it means 2 palettes of 4 colours, for example.

**Comment by Rangi42** [comment]
This is the same non-issue as #1074: `-c embedded` *does* accept embedded palettes with extra unused colors, and just ignores them.
