### ISSUE TITLE
RGBLINK is not compliant with the sym file spec

### ISSUE THREAD

**Issue by eievui5** [gbdev/rgbds#1076]
Spec: https://rgbds.gbdev.io/sym/
Parser: https://docs.rs/gb-sym-file/latest/gb_sym_file/

`!` is not allowed in symfiles according to the spec, but is used for anonymous labels. @ISSOtm suggested not outputting anything for anonymous labels.

**Comment by ISSOtm** [comment]
Not emitting anonymous labels is tricky without support from RGBLINK, since they must be emitted by RGBASM to be linkable. (Hence the unique names to begin with.)

It's possible to instead skip emitting symbols whose first character is non-conformant (note that the rest can and should simply use `\u` escapes), I'm just not sure if that's desirable.

**Comment by Rangi42** [comment]
I assumed this would be a feature of `rgblink` only, since it outputs the .sym files. That spec does not apply to the object files that rgbasm outputs; their labels can include whatever weird characters.

**Comment by ISSOtm** [comment]
I was considering whether there was a way to avoid changing RGBLINK, but it seems like this is not a possibility.

**Comment by ISSOtm** [comment]
Actually, RGBLINK in its entirety is not compliant: not only does it allow symbols beginning with illegal letters, it also emits illegal characters as-is instead of `\u` sequences.
