### ISSUE TITLE
Zelda disassembly ROM has changed with v0.6.0

### ISSUE THREAD

**Issue by tobiasvl** [gbdev/rgbds#1093]
https://github.com/zladx/LADX-Disassembly now builds a slightly different ROM with RGBDS v0.6.0 than with v0.5.2.

The changes seem to be related to graphics, and so they probably come from RGBGFX. Not sure how to debug this, but perhaps someone here recognizes what might cause this?

Diff of the resulting ROMs (RGBDS v0.5.2 on the left, v0.6.0 on the right):

![image](https://user-images.githubusercontent.com/80824/194773885-5736a3d5-8743-4d55-9a7a-15946c2763b1.png)

**Comment by Rangi42** [comment]
Your [Makefile](https://github.com/zladx/LADX-Disassembly/blob/main/Makefile) invokes `rgbgfx` like this:

```Makefile
2BPP    := rgbgfx

...

# Compile a PNG file to a 2BPP file, without any special conversion.
# (This typically uses `rgbgfx`, which is much faster than the
# Python-based `gfx.py`.)
%.2bpp: %.png
	$(2BPP) -o $@ $<
```

This used to Just Work because it would try to guess the right palette to use, and happen to be successful; but this was fragile and could change based on invisible details of the PNG encoding. Now you should explicitly pass `-c <palette_spec>` to specify what palette you want.

If all of your PNGs use the same four monochrome colors, you can list those directly, e.g. `-c '#000,#555,#aaa,#fff'`.

**Comment by tobiasvl** [comment]
Thank you! To be clear, I'm just a user of that repo, not a maintainer, so it's not my Makefile or PNGs :) But it's open source, so I can of course submit a PR to the project and fix the palette(s).

However, it's not clear to me why it used to "Just Work" but doesn't anymore. Judging by the changelog and documentation, the `-c` flag was added as an alternative to the automatic palette detection, which still is present, even though your comment seems to imply it's deprecated and/or at least strongly discouraged. But it seems to just detect the wrong palette for one PNG (I haven't looked closely at the tile data, but judging by the small diff I assume it's just one), so that must mean the actual detection algorithm has changed somehow as well?

**Comment by Rangi42** [comment]
0.5.2 used to use an embedded indexed palette if one was available, otherwise generate a palette sorted from darkest to lightest. 0.6.0 no longer does this; always generating a palette, or always using an indexed one when passed `-c embedded`, is more predictable.

What does `file the/bad/image png` output? I'll bet it has an indexed palette which, if viewed in a program like Aseprite or GIMP that doesn't totally hide internal palettes, shows an order different than the default grayscale order.

Solution: re-save the image as 2-bit grayscale like the rest probably are.

**Comment by tobiasvl** [comment]
I see, that makes sense. What I mean is that I'm still not clear on why 0.6.0 (without a `-c` flag) would generate a different palette than 0.5.2 on the same un-indexed image though. Something in the algorithm that guesses or generates the palette must have changed?

But tracking down and fixing the offending image seems like the best solution regardless, thanks!

**Comment by tobiasvl** [comment]
OK, I found it right away actually. It's an image with only three colors, which might explain things: https://github.com/zladx/LADX-Disassembly/blob/main/src/gfx/items/slime_key.cgb.png

**Comment by eievui5** [comment]
> I'm still not clear on why 0.6.0 (without a `-c` flag) would generate a different palette than 0.5.2 on the same un-indexed image though.

We removed the indexed-first behavior because there was some worry that it was confusing and incompatible with some editors. Clearly making a breaking change like this was a bad idea and we’ll keep this in mind going forward, but for now we’re stuck with 0.6.0 as it is.

**Comment by tobiasvl** [comment]
Right. I'm not sure if I'm still misunderstanding or not, but the image that gets a different palette with 0.6.0 doesn't have an indexed palette, so the removal of the indexed-first behavior seems irrelevant to me.

**Comment by ISSOtm** [comment]
RGBGFX v0.6.0 generates the same tile data for this image as v0.5.2:

```
issotm@sheik-kitty ~/LADX-Disassembly% ~/rgbds/rgbgfx -o src/gfx/items/slime_key.cgb.2bpp src/gfx/items/slime_key.cgb.png 
issotm@sheik-kitty ~/LADX-Disassembly% rgbgfx -o /tmp/slime_key.cgb.2bpp src/gfx/items/slime_key.cgb.png
issotm@sheik-kitty ~/LADX-Disassembly% hexyl src/gfx/items/slime_key.cgb.2bpp    [main|✔] 
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 00 00 18 18 3c 24 3c 24 ┊ 7e 42 ff 99 ff a5 ff a5 │00••<$<$┊~B××××××│
│00000010│ ff 99 7e 42 3c 3c 1c 14 ┊ 7c 74 7c 54 7c 44 7c 7c │××~B<<••┊|t|T|D||│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
issotm@sheik-kitty ~/LADX-Disassembly% hexyl /tmp/slime_key.cgb.2bpp             [main|✔] 
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 00 00 18 18 3c 24 3c 24 ┊ 7e 42 ff 99 ff a5 ff a5 │00••<$<$┊~B××××××│
│00000010│ ff 99 7e 42 3c 3c 1c 14 ┊ 7c 74 7c 54 7c 44 7c 7c │××~B<<••┊|t|T|D||│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
issotm@sheik-kitty ~/LADX-Disassembly% ~/rgbds/rgbgfx -V                         [main|✔] 
rgbgfx v0.6.0-8-g0e0876b1
issotm@sheik-kitty ~/LADX-Disassembly% rgbgfx -V                                 [main|✔] 
rgbgfx v0.5.2
```

The DMG one, however, does not:

```
issotm@sheik-kitty ~/LADX-Disassembly% rgbgfx -o src/gfx/items/slime_key.dmg.2bpp src/gfx/items/slime_key.dmg.png
issotm@sheik-kitty ~/LADX-Disassembly% ~/rgbds/rgbgfx -o /tmp/slime_key.dmg.2bpp src/gfx/items/slime_key.dmg.png
issotm@sheik-kitty ~/LADX-Disassembly% hexyl src/gfx/items/slime_key.dmg.2bpp    [main|✔] 
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 00 00 18 18 3c 24 3c 24 ┊ 7e 42 ff 99 ff a5 ff a5 │00••<$<$┊~B××××××│
│00000010│ ff 99 7e 42 3c 3c 1c 14 ┊ 7c 74 7c 54 7c 44 7c 7c │××~B<<••┊|t|T|D||│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
issotm@sheik-kitty ~/LADX-Disassembly% hexyl /tmp/slime_key.dmg.2bpp             [main|✔] 
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 00 00 00 18 18 24 18 24 ┊ 3c 42 66 99 5a a5 5a a5 │000••$•$┊<Bf×Z×Z×│
│00000010│ 66 99 3c 42 00 3c 08 14 ┊ 08 74 28 54 38 44 00 7c │f×<B0<••┊•t(T8D0|│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```

This is why:

```
issotm@sheik-kitty ~/LADX-Disassembly% ~/rgbds/rgbgfx -vvv -o /tmp/slime_key.dmg.2bpp src/gfx/items/slime_key.dmg.png
rgbgfx v0.6.0-8-g0e0876b1
Options:
	Bit depth: 2bpp
	Maximum 8 palettes
	Palettes contain 4 colors
	No palette spec
	Input image slice: 0x0 pixels starting at (0, 0)
	Base tile IDs: [0, 0]
	Maximum 65535 tiles in bank 0, 0 in bank 1
	Input image: src/gfx/items/slime_key.dmg.png
	Output tile data: /tmp/slime_key.dmg.2bpp
Ready.
Using libpng 1.6.38
Reading tiles...
Opened input file
PNG header signature is OK
Input image: 8x16 pixels, 2bpp palette, not interlaced
Embedded palette has 4 colors: [#ffffffff, #aaaaaaff, #555555ff, #000000ff]
Image colors: [ #000000ff, #aaaaaaff, #ffffffff, ]
Image contains 1 proto-palette
[ $0000, $56b5, $7fff, ]
Paginating palettes using "overload-and-remove" strategy...
{ [0] 0000, 56b5, 7fff, } (volume = 3)
{ [0] 0000, 56b5, 7fff, } (volume = 3)
Proto-palette mappings: (1 palette)
0 -> 0
Sorting palettes using embedded palette...
{ 7fff, 56b5, 0000, }
Generating unoptimized tile data...
```

Notice the last three lines: the image is not detected as grayscale because it contains an embedded palette. Since d86d24bdc14fb2fc5c1ca9729495e1a26c2d6d08, unused entries are ignored, so black (entry #3 in the embedded palette) is set into slot #2 instead of #3. Marking the image as non-indexed fixes this transparently, since that sorting algorithm does what you're looking for.

That said, despite opening the PR above, I'd generally advise relying on `-c` instead; while it does break compatibility with earlier versions, it does not have any of the implicit and surprising behaviour of default colour sorting, since it's important.

If all images do use the same palette of four grays, you can hardcode it directly into your Makefile; if they don't, you can try using [at-files](https://rgbds.gbdev.io/docs/v0.6.0/rgbgfx.1/#At-files). I don't know what would work best for you.

**Comment by tobiasvl** [comment]
Thanks so much, @ISSOtm! Both for finding the correct image and fixing the problem, and explaining it so thoroughly with commands on how to troubleshoot it. (And thanks to everyone else too, and your patience.)
