### ISSUE TITLE
Win32 and Win64 releases cannot be downloaded

### ISSUE THREAD

**Issue by jojobear13** [gbdev/rgbds#1136]
The links for the zip files appear to be broken.

**Comment by avivace** [comment]
> The links for the zip files appear to be broken.

Where do you see the broken links?

Check https://github.com/gbdev/rgbds/releases/tag/v0.6.1

**Comment by jojobear13** [comment]
My apologies. This was caused by Avast Antivirus shitting the bed. It seems to think that the links to the windows zips are malicious.

**Comment by ISSOtm** [comment]
Alright then, thank you for your time regardless ^^

**Comment by avivace** [comment]
> Alright then, thank you for your time regardless ^^

It would be interesting to understand why the releases are flagged as malicious by Avast.. :/

**Comment by tobiasvl** [comment]
I have no idea how Avast works, but Windows itself also warns about potential danger when downloading unsigned binary files that haven't been downloaded many times before (by anyone who's allowed Windows to track telemetry data like that). Perhaps it's something similar? I'm not sure if signing the binaries is a solution?

**Comment by pinobatch** [comment]
For Microsoft Defender in particular, the relevant keywords are `SmartScreen Application Reputation`. From [Microsoft's description of SmartScreen](https://learn.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview):
> **Reputation-based URL and app protection:** Microsoft Defender SmartScreen evaluates a website's URLs to determine if they're known to distribute or host unsafe content. It also provides reputation checks for apps, checking downloaded programs and the digital signature used to sign a file. If a URL, a file, an app, or a certificate has an established reputation, users won't see any warnings. If there's no reputation, the item is marked as a higher risk and presents a warning to the user.

From [SmartScreen FAQ](https://fb.smartscreen.microsoft.com/smartscreenfaq.aspx):
>  **What does it mean when Microsoft Defender SmartScreen marks a downloaded program as ‘not commonly downloaded’?**
> 
> Microsoft Defender SmartScreen uses information from Internet Explorer, Microsoft Edge, and Windows users around the world as well as anti-virus results, download volumes, download history, URL reputation, and many other criteria to determine the likely risk of downloaded programs. For example, programs that are downloaded by many users over a long period of time without a history of malware are not likely to be malicious.
> 
> This warning indicates that caution should be taken before running the downloaded program, especially if the download is not digitally signed. 
> 
> **If I am an application owner, what can I do to help minimize the chance of my program being flagged as “not commonly downloaded” by Microsoft Defender SmartScreen?**
> 
> To help establish your application's reputation, consider doing the following:
> 
> **Digitally sign your programs with an Authenticode signature**
> Reputation is generated and assigned to digital certificates as well as specific files. Digital certificates allow data to be aggregated and assigned to a single certificate rather than many individual programs. Only Authenticode Certificates issued by a Certificate Authority (CA) that is a member of the Windows Root Certificate Program can establish reputation.

Conspicuous by its absence from the latter document is how an informal organization of hobbyists maintaining a software development toolchain distributed as free software ought to be able to afford to obtain and renew "Authenticode Certificates issued by a Certificate Authority (CA) that is a member of the Windows Root Certificate Program." Unlike in the case of TLS, there are no free Authenticode certificates because there are no domain-validated (DV) Authenticode certificates. Code signing conventionally requires at least organization validation (OV) because the session secured by an Authenticode certificate is the entire life of an executable on the user's offline machine. This makes it less practical to check for revocation than in the case of TLS where a session lasts minutes and server operators are encouraged to staple an OCSP response from the CA.

**Comment by aaaaaa123456789** [comment]
> Code signing conventionally requires at least organization validation (OV) because _that way the CAs, in tandem with root certificate programs, can extort more money from developers_.

Fixed that for you

**Comment by jojobear13** [comment]
Avast thinks that the link to 0.6.1 win64 is some kind of trojan.
![image](https://user-images.githubusercontent.com/47074297/225325726-0dbf4648-d53a-4500-8bbc-015b0aeefc4d.png)

I haven't the slightest clue why as 0.6.0 is totally fine.

**Comment by pinobatch** [comment]
If Avast is behaving anything like SmartScreen, this sounds like 0.6.0 has built up reputation and 0.6.1 has not yet built up reputation.

**Comment by aaaaaa123456789** [comment]
This isn't a reputation-based detection: it's detecting an actual trojan, not a "potentially insecure URL" or however reputation services call them. (I prefer "we hate small devs", but that's just me.)

This is a plain old false positive.

**Comment by pinobatch** [comment]
I looked at the [form for reporting false positives to Avast](https://www.avast.com/false-positive-file-form.php#pc). Most provisions in the linked "[Avast Clean Guidelines](https://support.avast.com/en-ww/article/228/#pc)" look sensible, though some appear unfriendly to nonprofit efforts and others GUI where you have an installer that drops a single executable into a system folder rather than a set of smaller loose executables.

> **Advertising**
> **Prohibited:**
> 1\. **Misleading ads**
> (e) Advertising a free product for a cost.

This appears to prohibit offering a program as part of a pay-what-you-want bundle.

> **Installation process**
> **Recommended:**
> 1\. **Signing software**
> (b) Availability of a digital signature is preferred.

This one is better, as it doesn't mention Authenticode in particular, allowing for things like OpenPGP where users have settled on trust-on-first-use.

> **Must have:**
> 1\. **Bundling software**
> (b) Each program must be offered on its own offer/install screen with clear information about its functionality, behavior, cost (if applicable) and purpose.

The wording of this provision appears not to anticipate a software development toolchain broken into multiple executables.

> **Uninstallation process**
> **Must have:**
> (c) Include a corresponding 'Add/Remove' entry in the Windows Control Panel or equivalent on different platforms, and the user must be able to completely uninstall the software.

The wording of a requirement for an entry in the Control Panel appears to mean that an application must have an explicit installer (even if only to have an uninstaller), as opposed to being "portable" in the sense of designed to run from a directory in the user's profile or on removable media.
