### ISSUE TITLE
Fix CI warnings about unknown printf format conversions

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1183]
The Windows builds give a lot of "`unknown conversion type character ‘z’ in format`" warnings for `%zu` for `size_t`, and some about `‘j’` for `%j` for `intmax_t`. We could define custom `PRI*`-like macros for those data types, depending on the platform's size of those types.

The combinations we use: `%zd %zu %jd %ju %jx`

**Comment by Rangi42** [comment]
MSVC [uses nonstandard](https://learn.microsoft.com/en-us/previous-versions/tcxf1dw6(v=vs.140)?redirectedfrom=MSDN) `%Iu` instead of `%zu` for `size_t`, `%I` instead of `%t` for `ptrdiff_t`, and doesn't support `%j` for `intmax_t`.

**Comment by CasualPokePlayer** [comment]
Those are old non-standard extensions in MS's CRT, which even you'd have to be linking to an ancient C runtime to have issues here. The newer C runtimes (at least since 2015) support %zu and %t and %j just fine: https://learn.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-140#size-prefixes-for-printf-and-wprintf-format-type-specifiers

**Comment by Rangi42** [comment]
So it's specifically `windows-xbuild` that has this issue, because it compiles with `mingw32-gcc` / `mingw32-g++`. Annoying but not a significant issue.

**Comment by Rangi42** [comment]
Or, not an issue at all; the warnings don't signify an actual problem, and they're not RGBDS's responsibility.
