### ISSUE TITLE
[Feature request] 24-bit (3-byte) data support

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1511]
RGBDS has `db`/`rb` for 8-bit bytes, `dw`/`rw` for 16-bit words, and `dl`/`rl` for 32-bit "long words". This leaves a gap for 24-bit values, which have various use cases both during assembly and runtime (bank+address, RGB888 color, any time you need "millions" of values but still with a fourth byte to spare).

Prior terminology is uncommon, since historically 24-bit machines just called these "words" (the [eZ80](https://www.zilog.com/docs/um0077.pdf) even referred to "16-bit words" and "24-bit words" on the same platform!), and then we settled on powers of 2 for everything. Some examples do exist:

- WLA-DX uses `.DL` for for 24-bit "long words", and `.DD` for 32-bit "double words". (But we can't use `dl`/`rl` because RGBDS's "long"s are different.)
- Wikipedia [claims](https://en.wikipedia.org/wiki/24-bit_computing) "The term `SWORD` is sometimes used to describe a 24-bit data type with the `S` prefix referring to '[sesqui](https://en.wiktionary.org/wiki/sesqui)'." (But we can't use `ds`/`rs` because `ds` is already a "define space" keyword. (And `rs` is not a keyword, but `_RS` is a symbol.))
- MySQL uses `TINYINT`, `SMALLINT`, `MEDIUMINT`, `INT`, and `BIGINT` for 1-, 2-, 3-, 4-, and 8-byte values respectively. (We could use `dm`/`rm`? Although I don't like how "`rm`" looks like "remove".)
- StackExchange [mentions](https://softwareengineering.stackexchange.com/a/162034) "tribyte" as a common term in some contexts. (We could use `dt`/`rt`?)
- pokecrystal uses a `dt` macro for three-byte big-endian values. (pret could change that to `bigdt` if RGBDS uses `dt`/`rt` -- frankly they should anyway, to make the endianness obvious and to match their `bigdw` macro.)

Overall, I'd prefer adding `dt`/`rt` keywords for "tribyte" data.

**Comment by ISSOtm** [comment]
Thank you for your research, thorough as always :)

I don't feel convinced by this feature, because the primary use case, “far pointers”, are heterogeneous and I believe that `(bank, ptr)` is roughly as common as `(ptr, bank)`.
And also because I have thus far *never* witnessed a use of `dl`, not even emulated by `dw`s due to a lack of awareness.

The other use cases, I feel are niche enough to be emulated using `db`s for RGB888 (`db $12,$34,$56,  $78,$9A,$BC` is *fine*..? And that's assuming you want the components stored in RGB order, too; `dt` would give you BGR.) or warrant writing a macro.

**Comment by Rangi42** [comment]
Yeah, that's fair. Pokemon uses a few 3-byte values (e.g. for money and experience) but some of those would need a macro anyway for being big-endian or BCD, so plain `dt` wouldn't get much use. (Probably more than `dl`, but still not a lot.)
