### ISSUE TITLE
Missing `ENDL` after `LOAD` is not an error

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1534]
At the *very least* this should be a warning, and I expect it should be an error like other missing terminators (`ENDC`, `ENDR`, `ENDU`, etc).

```asm
section "rom", rom0
Label::
db 1, 2, 3
dw startof("rom"), sizeof("rom")
load "ram", wram0
wLabel::
db 4, 5, 6
dw startof("ram"), sizeof("ram")
```

**Comment by JL2210** [comment]
I propose making this a feature. I don't see any inherent reason why `LOAD` blocks have to be different than sections with regard to termination. It would certainly make e.g. implementing global variables in a C compiler a lot easier, in combination with #1535. All it would need is a simple copy of memory rather than initializing every global variable independently.

**Comment by JL2210** [comment]
Not exactly the same issue but missing `ENDS` after `PUSHS` is not an error or a warning either

**Comment by ISSOtm** [comment]
Okay&mdash;I can see us giving `LOAD` similar semantics as `SECTION`, where they can implicitly “override” each other. This would make behaved `ENDL` similarly to `ENDS`.

We could add a `-Wextra` warning about not using `ENDL`. *Maybe?*

**Comment by aaaaaa123456789** [comment]
What happens if you use `SECTION` within a `LOAD` block? I can see two possible behaviors: hard error or terminate the load block implicitly (along with the containing section).

**Comment by Rangi42** [comment]
I would expect it to terminate the current section+load block, and start a new section.
