### ISSUE TITLE
Deprecate `ld [c], a` and `ld a, [c]`

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1573]
`ldh [c], a` and `ldh a, [c]` are preferred.

The [opcode table](https://gbdev.io/gb-opcodes/optables/classic) should also be updated.

**Comment by nummacway** [comment]
Don't know if this needs its own issue, but documentation for one command uses an uppercase and the other a lowercase C to refer to the address (`$FF00+C` vs. `$FF00+c`). This should be made consistent. One might even want to spell this out, because this is the only case of C having a special purpose:
> Copy the value in register A into the byte at address _$FF00+C_ ($FF00 plus the unsigned value in register **C**).
