### ISSUE TITLE
Implement string formatting syntax in RGBASM

### ISSUE THREAD

**Issue by PikalaxALT** [gbdev/rgbds#178]
Implement a function, `STRFMT(spec, ...)` which takes string `spec` and formats following arguments into the fields specified in spec, similar to `std::printf`.  Minimally, support %s, %d, %f, %x.

    VAL1 = STRFMT("Hello %s! I am %d years old today!", "world", $f)
    PRINTT "{VAL1}\n"
should yield

    Hello world! I am 15 years old today!

**Comment by ekimekim** [comment]
This would be the ideal general solution, though right now i'd settle for just some way to format a value as decimal rather than hex.

**Comment by ISSOtm** [comment]
Fact: we will not be passing the string directly to `printf` because of not trusting user input (say hi to `%n`) and trying to parse the string for sanitization amounts to, well, parsing it ourselves.

Considering this, what features would be desired? (Zero-padding, minimum lengths, argument reordering perhaps?)

**Comment by AntonioND** [comment]
I would keep it simple. No argument reordering. Probably minimum leading zeroes/spaces.

**Comment by Rangi42** [comment]
Leading zeros/spaces, and `d/x/X/b/o` to support the same integer bases for which there are literals.

Also maybe trailing spaces with `-`. So `STRFMT("%-4d", N)` where `N == 42` gives `"42  "`. Or `STRFMT("%-10s", Hi)` where `Hi` is `"hello"` gives `"     hello"`.
