### ISSUE TITLE
{symbol} should work in label names

### ISSUE THREAD

**Issue by obskyr** [gbdev/rgbds#269]
In macros, the following works:
```asm
AMacro: MACRO
ALabel\1::
    ; ...
ENDM

x EQUS "Hello"
AMacro {x}
```

However, despite the fact that macro arguments expand just fine in label names, and insta-expanded symbols work fine in macro arguments, insta-expanded symbols don't work in label names:

```asm
x EQUS "Hello"
ALabel{x}::
    ; ...
```

For consistency (and usefulness!), they should.

**Comment by ISSOtm** [comment]
This is the case with all symbols, really.

The reason why it works with macros is because the lexer expands `{x}` when lexing the macro arguments, and correctly pasted inside the macro as you'd expect.

The way such "pasting" works is super wonky anyways, so this is like #485: quite a long-term effort to fix right. And I don't want a quick fix because `lexer.c` is enough of a pile of hacks as-is.

**Comment by Rangi42** [comment]
Permitting `{symbol}` interpolation anywhere, once the new lexer allows it, would be quite helpful for making dynamic macro code less complicated, without having to define and purge temporary strings. For instance, this:

```
_TMP EQUS "PURGE {METAFOO}"
    _TMP  ; PURGE FOO, assuming METAFOO currently EQUS "FOO"
    PURGE _TMP, METAFOO
```

could be simply this:

```
    PURGE {METAFOO}, METAFOO
```

And this:

```
IF n < 10
MOVE_FOR_TM EQUS "TM0{d:n}_MOVE"
ELSE
MOVE_FOR_TM EQUS "TM{d:n}_MOVE"
ENDC
	db MOVE_FOR_TM
PURGE MOVE_FOR_TM
```

could be simply this:

```
IF n < 10
	db TM0{d:n}_MOVE
ELSE
	db TM{d:n}_MOVE
ENDC
```

(or even just `db TM{02d:n}_MOVE` if interpolation had more printf-like capability)

**Comment by Rangi42** [comment]
This should be closed, right? The new lexer isn't going to support `{symbol}` outside strings.

**Comment by ISSOtm** [comment]
Since it's essentially been superseded by #629, I'm okay with that now.
