### ISSUE TITLE
[Feature request] Variable macro argument expansions

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#460]
What I'm asking for here is some syntax of the form `\(<expr>)` (or `\{<expr>}` or anything like that) that would get replaced with the corresponding macro argument. For instance, `\(1)` would be equivalent to what `\1` does currently.  
If RGBASM cannot work out the value of the expression, or if it comes out to a non-positive value or a value above the number of macro arguments, it should issue an error (or a warning and a blank substitution).

Potential uses:

1. Macro arguments above 9. Long macros are forced to use `shift`; this makes them harder to read. `\(10)` would be easier to understand.
2. Macros with variable argument lists. Most of these can be done with `shift` (and some creative usage of variables), but they could be far more straightforward this way. A simple, trivial example:
```
reversedb: MACRO
___current = 0
  rept _NARG
    db \(_NARG - ___current)
___current = ___current + 1
  endr
ENDM
```

Thoughts? Ideas?

**Comment by ISSOtm** [comment]
I had another, broader idea, which was basically allowing `#define`-style macros. They would have named arguments, their arguments would be entire tokens (meaning, less quirks about the expansion), and should be usable inline. That would (probably, right?) solve a lot of issues we currently have.

**Comment by aaaaaa123456789** [comment]
Both are good ideas. I don't think they necessarily replace one another.

**Comment by ISSOtm** [comment]
Allowing expressions inside the parentheses would be really complicated, as macro expansions are done by the lexer (and would have to be kept that way for compatibility), so we'd have to reimplement a lot of arithmetic into the lexer... I'm not comfortable with implementing this at all. That's why I'm leaning more towards defining something else entirely.

**Comment by Rangi42** [comment]
What if `'\0` expanded to "all the remaining un`shift`ed arguments, comma-separated"? That would allow simplifying something like this:

```
person_event: MACRO
;	object_event \3, \2, \1, \4, \5, \6, \7, \8, \9, \10, \11, \12, \13
	db \1, \2 + 4, \3 + 4, \4
	dn \6, \5
	db \7, \8
	shift
	dn \8, \9
	shift
	db \9
	shift
	dw \9
	shift
	dw \9
ENDM
```

to this:

```
person_event: MACRO
	object_event \3, \2, \1, \0
ENDM
```

**Comment by AntonioND** [comment]
In `argv`, argument 0 is the path of the binary. In a macro, I would expect something like the name of the macro.

I think your use-case is interesting, but I think it would be much clearer to have it as `\all` or something like that.

**Comment by Rangi42** [comment]
Assuming a single-character limit, `\*` would also make sense, but 0 is a unused digit in case that makes it easier to implement. (Also I think "`\0`" makes sense compared to regexes, where `\0` is the whole match and `\1`+ are individual capture groups.)

**Comment by AntonioND** [comment]
I just think that 0 is confusing. However, `\*` looks reasonable to me.

**Comment by Rangi42** [comment]
`\#` now expands to all unshifted macro arguments as of #641, fixing #596.

Regarding the original request here to add `\(expr)` / `\{expr}` for the `expr`th macro argument, what about just allowing `\([0-9]+)` for multi-digit argument numbers?

**Comment by aaaaaa123456789** [comment]
Consider the case where the macro argument expansion is followed by a digit...

**Comment by Rangi42** [comment]
You mean like `\(10)4` where argument 10 expands to `123`? Then it would become `1234`, just like if `\9` were `123` in `\94`, or `N` were `123` in `{N}4`.

**Comment by aaaaaa123456789** [comment]
Ah, I interpreted the parens as regex grouping. Would there be any way to evaluate an expression into the parens? (Perhaps by abusing strings... again)

**Comment by Rangi42** [comment]
I don't think expressions would be possible since as discussed above, expression evaluation is done by the parser, and macro argument expansion is done by the lexer.

**Comment by Rangi42** [comment]
How much should be allowed within the parentheses of `\(...)`?

It could just allow ASCII digits, using `peekInternal` to read them. This would be relatively easy to handle but inconsistent with how you can put macro args, interpolations, and line continuations inside other syntax (like `$1{d:n}4` where `n EQU 23` for `$1234`, or `foo "a,  b` where `foo: MACRO db \1 x \2" ENDM` for `db "a x b"`).

It could also use `peek` to read the digits of `\(...)`. So `ld a, \(S)` where `S EQUS "10"` would give `ld a, \(12)`; and `db \(1\1)` where `\1` expands to `23` would give `db \(123)`. This might be tricky, because something would be expanded inside the parentheses, but then the parenthesized number would cause another expansion that "overrides" that one. (E.g. in `ld a, \(S)`, an expansion turns `S` into `10`, and then an expansion turns `\(10)` into the contents of macro arg 10—let's say that's "`NUM+2`"—and the "main" lexer should just see `ld a, NUM+2` as it continues calling `peek`, without missing any characters or seeing the "inner" `10` expansion.)

Also, `readString` would need to toggle `disableMacroArgs` and `disableInterpolation` correctly for its own `readMacroArg` handling call. With edge cases like:

```
foo: MACRO
    PRINTT "Hello \(\1
ENDM
    foo 2)!\n", world
```

Would the expansion of `\1` give the valid `PRINTT "Hello \(2)!\n"`, which then becomes `PRINTT "Hello world!\n"`? That would match the behavior of 0.4.2, but not of current `master`. Here:

```
foo: MACRO
 db "A\1D"
ENDM

 foo B"\, "C
```

This acts like `db "AB", "CD"` in 0.4.2, but acts like `db "AB\", \"CD"` in `master` (upcoming 0.4.3/0.5.0).

**Comment by ISSOtm** [comment]
I'll close this, treating it as superseded by `\#`. If you need argument N, expand `\#`, split on commas, and pick the Nth element. If someone finds this unsatisfactory, I will reopen this; but for now, the difficulty in implementing the original request, on top of a suitable workaround existing, makes this very unlikely.
