### ISSUE TITLE
Settle over code style and whether to use `clang-format`

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#612]
Okay, we have a problem where our code style is not properly enforced, and not even properly defined for that matter. We're pointing at the Linux style guide, but also making a bunch of undocumented amendments to it (our `checkpatch` flag overrides).

Further, people have complained about there being no automated way to reformat the code, and providing a `clang-format` style sounds like a good way to fix that.

But, since we're formalizing the style, now would also be a good time to revisit it entirely. Being the single main contributor, I don't like many parts of it, such as requiring a blank line after each declaration, or banning C++-style comments (that became irrelevant since we're requiring C11). This issue is also for input from others, especially @AntonioND and @JL2210, being the other two active and regular contributors. **> Everyone <** is welcome to participate, since this is part of an effort to make the codebase more accessible!

The two reasons why I haven't changed the style yet are consistency, and not wanting to trash `git blame`. But if we're making a tool do it, the former isn't an issue; and we don't do the latter frequently enough that it's a real problem.

**Comment by AntonioND** [comment]
The reason why I picked the Linux style was because of the easy availability ``checkpatch.pl``. I find ``clang-format`` super annoying to set up. I've tried a few times. There are way too many options and some things like aligning define values aren't allowed, and pretty much everyone likes to align them.

However, ``clang-format`` checks and fixes the format, which is useful.

I guess that if someone comes up with a decent configuration file, it's fine.

**Comment by aaaaaa123456789** [comment]
The Linux kernel has a large number of fringe targets that require restricting the language heavily. Code that doesn't belong to an intentionally overly portable OS kernel should use a more modern code style; I agree that there is no point in banning `//` comments or other similar new features.

As for everything else, consistency (and not picking an intentionally hard to read format such as GNU's or pret's) is pretty much the single main point when it comes to accessibility. The actual code style in use should be whatever the main maintainer(s) find more readable, since they're going to be reading that code more often than anyone else.

**Comment by AntonioND** [comment]
> The Linux kernel has a large number of fringe targets that require restricting the language heavily. 

Restrictions like what?

Regarding ``//``, I remember that even Linus has mentioned at some point that it made no sense to restrict them right now, and that he is happy to move to C++ style: http://lkml.iu.edu/hypermail/linux/kernel/1607.1/00627.html Personally I use ``//`` everywhere nowadays.

> As for everything else, consistency (and not picking an intentionally hard to read format such as GNU's or pret's) [...]

Nobody should use GNU's coding style.

**Comment by Rangi42** [comment]
Now that `//` comments are acceptable, it may be worth standardizing on them for all single-line comments. (I'd wait until the large PRs #685 and #712 are merged for that.)

**Comment by Rangi42** [comment]
I mostly like the current code style (tab indentation, open brace on the same line, closing brace on a new line, spaces around operators, etc), except for the blank lines after declarations and the frequent `/* comments */`.

I wouldn't mind standardizing to require braces even for single-line blocks.

I'd also like to standardize on `// comments` when they're only one line.

**Comment by daid** [comment]
Not using `//` in C already felt silly in 20 years ago, when every compiler already supported it, even if it wasn't standardized.

I did a project with clang-format on build, which I liked a lot more then I would have expected. And is solves a whole bunch of (useless) style discussions. Disadvantage could be that you need to install yet another tool, and that the available options differ quite a bit between versions of clang-format, which can cause large diffs if you are not careful.
