### ISSUE TITLE
[Feature request] Argument-less `rb`, `rw`, `rl`

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#617]
This one should be self-explanatory. `rb`, `rw` and `rl` by themselves should be equivalent to using them with an argument of 1. This would mirror, say, the usage of `db` and `dw` to declare the space for the corresponding data in WRAM.

**Comment by Rangi42** [comment]
This is sufficient to support no-argument `rb` and `rw`:

```
rw		: T_LABEL T_POP_RW uconst {
			sym_AddEqu($1, sym_GetConstantValue("_RS"));
			sym_AddSet("_RS", sym_GetConstantValue("_RS") + 2 * $3);
		} | T_LABEL T_POP_RW {
			sym_AddEqu($1, sym_GetConstantValue("_RS"));
			sym_AddSet("_RS", sym_GetConstantValue("_RS") + 2);
		}
;

rb		: T_LABEL T_POP_RB uconst {
			sym_AddEqu($1, sym_GetConstantValue("_RS"));
			sym_AddSet("_RS", sym_GetConstantValue("_RS") + $3);
		}
		| T_LABEL T_POP_RB {
			sym_AddEqu($1, sym_GetConstantValue("_RS"));
			sym_AddSet("_RS", sym_GetConstantValue("_RS") + 1);
		}
;
```

I'm having some trouble with `rl` since `foo rl 2` could be an RS command, or a colon-less label `foo` followed by a syntax errror Z80 `rl` opcode.

The rgbasm docs also say of `rl` "(In practice, this one cannot be used due to a bug)". Maybe rename `dl` and `rl` to `dg` and `rg` or `dn` and `rn` for "long"?

**Comment by Rangi42** [comment]
How about adding this feature without resolving the `rl` conflict, and leave that for #322?
