### ISSUE TITLE
Deprecate PRINTI/PRINTV/PRINTF/PRINTT in favor of one PRINT statement

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#669]
The multiple print statements can be confusing. For example, `PRINTI` and `PRINTV` do not match the `d` and `x` interpolation letters for decimal and hex numbers; `PRINTF` for fixed-point clashes with the standard C `printf()`; and with `STRFMT` and fancier interpolation, none of them are necessary.

I propose a single `PRINT` statement (or `ECHO`, or `PUT`, or whatever) that can take multiple comma-separated values and prints each one. Strings would be printed as-is; numbers would be printed with some default format (most likely uppercase hex with a `$` prefix, as a "least common denominator" for inspecting any sort of numeric value, similar to the default numeric interpolation format).

- `PRINTT "Hi!"` → `PRINT "Hi!"`
- `PRINTV 42` → `PRINT 42` or `PRINT STRFMT("%#x", 42)`
- `PRINTV FOO` → `PRINT FOO` or `PRINT "{FOO}"` or `PRINT "{X:FOO}"`
- `PRINTI 42` → `PRINT STRFMT("%d", 42)`
- `PRINTI FOO` → `PRINT "{d:FOO}"`
- `PRINTF 4.3` → `PRINT STRFMT("%.5f", 4.3)`

Sequences of print statements could sometimes be merged:

```
; old
    printt "2 + 2 ="
    printv 2+2
    printt "\n"

; new
    print "2 + 2 = ", 2+2, "\n"

; alt
    print strfmt("2 + 2 = %d\n", 2+2)
```

It may also be worth adding a `PRINTLN` statement, like `PRINT` but with a newline at the end, since that's such a common case.

**Comment by Rangi42** [comment]
Either of these could be easily implemented as a macro, so don't really *need* to be built-in, but I'd still appreciate built-in `PRINTLN`. (Which, without any parameters, would just print a newline.)

```
println: macro
    print \#, "\n"
endm

    println "2 + 2 =", 2+2

fprint: macro
    print strfmt(\#)
endm

    fprint "2 + 2 = %d\n", 2+2
```

**Comment by aaaaaa123456789** [comment]
This is definitely an improvement. `println` is definitely a good idea, although it could just as well be defined as a macro. `fprint` is probably not that great because it might be confusing due to the name clash with `printf`.

**Comment by Rangi42** [comment]
My issue with defining `PRINTLN` as a macro is that it would have to be redone all the time. Currently a lot of test cases do this:

```
print: MACRO
    printv \1
    printt "\n"
ENDM
```

#624 will fix #368 and make `PRINTV`/`PRINTI`/`PRINTF` emit a trailing newline. So all the test cases will be simplified to just do `printv X` instead of `print X` with the reiterated macro.

Going by this proposal, they'd be able to do `println X`, but without that they'd either need `print X, "\n"` or still have to define the same macro each time.

**Comment by Rangi42** [comment]
If this is acceptable, it would supersede #624 and #368: no need to update the behavior of things that are deprecated.

**Comment by aaaaaa123456789** [comment]
While I'd in general agree with that idea, adding or removing a newline is something so simple that it might be worth doing just to make it all uniform.

**Comment by Rangi42** [comment]
If `PRINT` and `PRINTLN` are added and `PRINTV`/`PRINTI`/`PRINTF`/`PRINTT` are deprecated, then at least *not* adding the trailing newline to them will let peoples' older code still work unchanged, albeit with deprecation warnings. Then when they're ready to revise it they can go straight to the new `PRINT`.

**Comment by ISSOtm** [comment]
That's what I'm thinking.

- I agree that the different print commands are, at this point, essentially cruft.
- *Changing* existing behavior like this is more problematic than adding and removing (changes to be made for upgrading are much more obvious)
- The old print statements *do* have obtuse names; I remember being confused at which was for what when I began. (It's not even "PRINTS" for a string, "PRINTN" for a number, and while "PRINTF" matches "print Fixed-point", it clashes with the much more well-known C function.)
- `STRFMT` is more flexible than any of the `PRINT`s, is more convenient, and is atomic. Behavior-wise (= ignoring compatibility), it's strictly a superset.

Given the change, I'm OK with breaking compatibility for that one.

I also wanted to deprecate e.g. `PRINTV` through the use of interpolation, but since it only works for symbols, I dropped the idea until `STRFMT` came into scope.
