### ISSUE TITLE
Avoid relying on floating-point for fixed-point

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#678]
Sparked from https://github.com/gbdev/rgbds/pull/675#discussion_r550764792: RGBASM currently converts fixed-point to floating-point, uses standard C functions for computation, and converts back. This may incur precision loss and lesser performance. I think it would be better to perform the operations in fixed-point as much as possible.

**Comment by Rangi42** [comment]
```
 printf MUL(3.1, 5.2) ; prints 16.11993
 assert MUL(3.1, 5.2) == 16.11994
 assert MUL(3.1, 5.2) == 16.12 ; Assertion fails
```

**Comment by Rangi42** [comment]
Some loss of precision is fundamental to the values being 16.16. In the above example:

```
3.1 -> 3+$1999/$10000
5.2 -> 5+$3333/$10000
3.1 * 5.2 = 16.12 -> 16+$1eb8/$10000
(3+$1999/$10000) * (5+$3333/$10000) = 16+$1eb4947b/$100000000 ≈ 16+$1eb4/$10000
$1eb4 ≠ $1eb8
```

Any multiplication algorithm, floating-point, fixed-point, or symbolic (100% accurate), would give the same result, since the initial operands had already been rounded to the nearest 65536th.

Here the floating-point and fixed-point both use power-of-2 fractions, so I expect that the conversion to/from fixed and floating point is 100% accurate, and fixed-point algorithms for multiply/sine/exponent/etc would not help.

**Comment by aaaaaa123456789** [comment]
Fixed point should be used for multiplication and division because it's simply faster, and also more accurate. (Assuming you have 64-bit types at your disposal, which you do.) In the example above, 3.1 should've been rounded to `$3199A` by the conversion — if it's reading it as `$31999`, it has a bug.

That being said, simple error propagation will tell you that multiplying well rounded values will result in a value accurate to 2 [ulp](https://en.wikipedia.org/wiki/Unit_in_the_last_place). So this can always happen.

**Comment by Rangi42** [comment]
Evaluating the source "`3.1`" to 0x3199A rather than 0x31999 is a matter of updating the lexer's `readFractionalPart`. However, after the value exists, converting to floating point with `fx2double` (divide by 65536.0) should not lose any precision.

As for performance of custom fixed-point math routines versus using the math.h floating-point ones, that's worth measuring, but I wouldn't be surprised if the current floating-point ones are faster, since CPUs are designed with them in mind. (It also keeps the code simpler, not having to implement various transcendental functions.)

**Comment by aaaaaa123456789** [comment]
If you're worried about precision loss on conversion, use `ldexp(value, -16)`. That is guaranteed to not lose any precision whatsoever in any reasonable implementation.

As for the functions you mention, I was only suggesting implementing in integer math the ones that have an obvious integer solution, such as multiplication (which is just `(x * y + 0x8000u) >> 16`).

**Comment by pinobatch** [comment]
If `readFractionalPart` and all other steps were updated to round to nearest, the result would be as follows:

`3.1 * 5.2` is thus `$3199a/$10000 * $53333/$10000`  
or `$3199a*$53333/($10000*$10000)`  
or `$101eb9c7ae/$100000000`  
Round to nearest 1/65536: `$101eba/$10000`  
or `16+$1eba/$10000` which equals 16.120026

This result is indeed 2 ulp off, an improvement from the 4 ulp of the current `readFractionalPart` implementation.
