### ISSUE TITLE
Piping input to rgbasm can fail in Windows x64 (MinGW or Cygwin)

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#689]
This is seen in a test case for #687, which fails in CI only for 64-bit Windows MinGW.

`test.asm`: (edited to not use `break` or `for`, only `rept/endr`)

```
V = 1
REPT 9
      PRINT "{d:V}, "
V = V + 1
ENDR
      PRINTLN "done {d:V}"

println "ready"
n = 1
rept 10
    println "step {d:n}:"
x = 0
    rept 10
        print "  x={d:x},"
x = x + 1
; This is a sufficiently long comment
; to make the piped case fail.
; Deleting it makes the pipe succeed.
; Probably something to do with buffer
; lengths in Cygwin/MinGW.
    endr
    println
    if n == 3
        println "halfway"
    endc
n = n + 1
endr
println "done"
```

Output of `rgbasm test.asm`:

```
1, 2, 3, 4, 5, 6, 7, 8, 9, done 10
ready
step 1:
  x=0,  x=1,  x=2,  x=3,  x=4,  x=5,  x=6,  x=7,  x=8,  x=9,
step 2:
  x=0,  x=1,  x=2,  x=3,  x=4,  x=5,  x=6,  x=7,  x=8,  x=9,
step 3:
  x=0,  x=1,  x=2,  x=3,  x=4,  x=5,  x=6,  x=7,  x=8,  x=9,
halfway
step 4:
  x=0,  x=1,  x=2,  x=3,  x=4,  x=5,  x=6,  x=7,  x=8,  x=9,
step 5:
  x=0,  x=1,  x=2,  x=3,  x=4,  x=5,  x=6,  x=7,  x=8,  x=9,
step 6:
  x=0,  x=1,  x=2,  x=3,  x=4,  x=5,  x=6,  x=7,  x=8,  x=9,
step 7:
  x=0,  x=1,  x=2,  x=3,  x=4,  x=5,  x=6,  x=7,  x=8,  x=9,
step 8:
  x=0,  x=1,  x=2,  x=3,  x=4,  x=5,  x=6,  x=7,  x=8,  x=9,
step 9:
  x=0,  x=1,  x=2,  x=3,  x=4,  x=5,  x=6,  x=7,  x=8,  x=9,
step 10:
  x=0,  x=1,  x=2,  x=3,  x=4,  x=5,  x=6,  x=7,  x=8,  x=9,
done
```

Output of `cat test.asm | rgbasm -`:

```
1, 2, 3, 4, 5, 6, 7, 8, 9, done 10
ready
ERROR: <stdin>(8) -> <stdin>::REPT~1(9):
    Unknown character 0xE0
ERROR: <stdin>(8) -> <stdin>::REPT~1(9):
    Unknown character 0xEF
ERROR: <stdin>(8) -> <stdin>::REPT~1(9):
    Unknown character 0x00
ERROR: <stdin>(8) -> <stdin>::REPT~1(9):
    Unknown character 0x00
ERROR: <stdin>(8) -> <stdin>::REPT~1(9):
    Unknown character 0x08
ERROR: <stdin>(8) -> <stdin>::REPT~1(9):
    Unknown character 0x00
[snip]
ERROR: <stdin>(8) -> <stdin>::REPT~10(16):
    Unknown character 0x00
done
error: Assembly aborted (541 errors)!
```

**Comment by Rangi42** [comment]
Note that this is not related to how non-stdin files can be `mmap`ped: when I comment that out and force `rgbasm test.asm` to open it as a regular file, it still succeeds.

**Comment by ISSOtm** [comment]
The problem is actually that `stdin` and `stdout` are opened in text mode by default on Windows, which translates CRLF to LF. (This was spotted while trying to fix #664.)

**Comment by ISSOtm** [comment]
Well, at least this is what I would assume, but it makes less sense if the bug happened from a *textual* input file... we'd need a reproducer.

**Comment by Rangi42** [comment]
That did not solve the original test case.

**Comment by Rangi42** [comment]
This issue is *inconsistently* triggered on CI for Windows by the `skip-elif-condition.pipe` test case ([example](https://github.com/gbdev/rgbds/runs/2213787692)), and potentially by others. (Re-running the tests, without any other changes, can fix these failures.)

**Comment by Rangi42** [comment]
[Here's](https://github.com/gbdev/rgbds/runs/2357705847) a case of what looks like this error being triggered by the `builtin-overwrite.pipe` test case on unix-testing (macos-10.15, clang, cmake).

**Comment by ISSOtm** [comment]
Great, another un-reproducible CI bug? --'

**Comment by NieDzejkob** [comment]
These are the exact tests that fail *consistently* with ASAN enabled!

**Comment by ISSOtm** [comment]
PogChamp

**Comment by ISSOtm** [comment]
The fact that this only occurs if large enough macros are run while piped (as indicated by @NieDzejkob in [the opening comment](https://github.com/gbdev/rgbds/pull/834#issue-616792869) of #834), and logs from that same PR:
```
freed by thread T0 here:
    #0 0x7ffff767983a in __interceptor_realloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:164
    #1 0x5555555d0bfa in reallocCaptureBuf src/asm/lexer.c:669
    #2 0x5555555d37ac in shiftChars src/asm/lexer.c:928
    #3 0x5555555d480d in nextChar src/asm/lexer.c:998
    #4 0x5555555db3b3 in lexer_CaptureMacroBody src/asm/lexer.c:2519
    #5 0x5555555e6c99 in yyparse src/asm/parser.y:996
    #6 0x5555555de370 in main src/asm/main.c:359
    #7 0x7ffff696eb24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
```
...point at the problem being a `realloc`'d pointer being stored across `realloc`s.

When `startCapture` is called, it returns a pointer to the beginning of the "capture buffer", which is what will be passed to the caller (macro, loop block, etc.). In the `mmap` case, excluding expansions due to lifetime concerns, this returns a pointer to the `mmap`ed data; otherwise, this begins a capture, and returns `lexerState->captureBuf`.

Regardless, this pointer will be written to `capture->body` at the end of the respective capture function (which doesn't make sense, it should rather be written then and there, which would've made the bug more obvious).
As you may have guessed, if the initial allocation is sufficient for the entire capture, this works fine, but if a `realloc` occurs, `reallocCaptureBuf` will modify `lexerState->captureBuf`, causing the UAF.
