### ISSUE TITLE
Find and fix RGBASM memory leaks

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#709]
- [x] `PURGE` or `REDEF` of an `EQUS` symbol does not free its previous string contents.
- [x] Use Bison to free memory when a token is deleted
- [x] Files are *never* `unmap`ed if a single macro or REPT block occurred within
- To be continued

**Comment by ISSOtm** [comment]
Believe it or not, but you can't free an `EQUS` :) I tried, and it explodes with a bunch of funny colors. The main problem is an expansion deleting itself; the solution is to ref-count strings. (This overlaps with #650.)

A large chunk of the problem is the lack of cleanup when done with assembling.

**Comment by ISSOtm** [comment]
Note that Bison's [token destructors](https://www.gnu.org/software/bison/manual/html_node/Destructor-Decl.html) might help with this a bit.

**Comment by Rangi42** [comment]
ASAN is enabled, but disables checking for memory leaks for now with `detect_leaks=0`.

**Comment by Rangi42** [comment]
See about using an '`std::shared_ptr` aliasing constructor' for dealing with `string_view`s that preserve the lifetime of a backing `std::string` (or mmap or whatever).
