### ISSUE TITLE
[Feature request] Variable arguments for `ds` like `db`/`dw`/`dl`

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#722]
[RASM](http://www.roudoudou.com/rasm/rasm_v112_en.pdf), like rgbasm, allows `ds N, V` to act like `db V, V, V, ...` with `N` values. However, it goes further and lets the `ds` take an arbitrary number of run-lengths. So `ds 3, "A", 4, "B"` would be like `db "AAABBBB"`.

Since the other data directives `db`, `dw`, `dl` all take multiple parameters, I think it would make sense for `ds` as well.

**Comment by ISSOtm** [comment]
Given that the parameters are heterogeneous, I'm not fond of making them repeat. Besides, why not use multiple lines for this? It makes sense for e.g. `db` since it can be followed by a lot of data, but I haven't seen `ds` need this at all. I would see a use for `ds cnt, byte1, byte2, byte3, ...` to repeat a more complex pattern, though.

**Comment by Rangi42** [comment]
Would it be more useful for `ds 5, $A, $B, $C` to output 5 bytes (`$A, $B, $C, $A, $B`) or fifteen (`$A, $B, $C` repeated 5 times)? Either way, I can update #725 to match.

**Comment by ISSOtm** [comment]
I think 5 bytes is more practical, since it allows achieving the latter via `ds 15, $A, $B, $C`.

**Comment by Rangi42** [comment]
Updated #725 so that `ds 5, $A, $B, $C` acts like `db $A, $B, $C, $A, $B`.
