### ISSUE TITLE
Build errors and warnings on FreeBSD

### ISSUE THREAD

**Issue by t6** [gbdev/rgbds#789]
I've added a package for rgbds to FreeBSD Ports, but had some trouble getting it to build. The error was
````
In file included from src/asm/charmap.c:22:
include/hashmap.h:18:15: error: expected parameter declarator
static_assert(HALF_HASH_NB_BITS * 2 == HASH_NB_BITS, "");
              ^
include/hashmap.h:17:27: note: expanded from macro 'HALF_HASH_NB_BITS'
#define HALF_HASH_NB_BITS 16
                          ^
include/hashmap.h:18:15: error: expected ')'
include/hashmap.h:17:27: note: expanded from macro 'HALF_HASH_NB_BITS'
#define HALF_HASH_NB_BITS 16
                          ^
include/hashmap.h:18:14: note: to match this '('
static_assert(HALF_HASH_NB_BITS * 2 == HASH_NB_BITS, "");
             ^
include/hashmap.h:18:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
static_assert(HALF_HASH_NB_BITS * 2 == HASH_NB_BITS, "");
^
1 warning and 2 errors generated.
````
This seems to be caused by the `-D_POSIX_C_SOURCE=200809L` in the Makefile. Removing it let's the build continue. Maybe the value is not quite right?

Clang also gives the following warnings on amd64 which might need some investigation
```
src/asm/util.c:60:30: warning: format specifies type 'unsigned char' but the argument has type 'int' [-Wformat]
                sprintf(&buf[2], "%02hhx", c);
                                  ~~~~~~   ^
                                  %02x
src/link/object.c:626:14: warning: result of comparison of constant 1152921504606846975 with expression of type 'unsigned int' is always false [-Wtautological-constant-out-of-range-compare]
        if (nbFiles > SIZE_MAX / sizeof(*nodes))
            ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
```
and some on i386
```
src/fix/main.c:678:16: warning: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Wformat]
                       name, rom0Len);
                             ^~~~~~~
src/fix/main.c:867:10: warning: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Wformat]
                       writeLen, name, rom0Len);
                       ^~~~~~~~
src/fix/main.c:867:26: warning: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Wformat]
                       writeLen, name, rom0Len);
                                       ^~~~~~~
src/fix/main.c:879:11: warning: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Wformat]
                               writeLen, name, totalRomxLen);
                               ^~~~~~~~
src/fix/main.c:879:27: warning: format specifies type 'long' but the argument has type 'size_t' (aka 'unsigned int') [-Wformat]
                               writeLen, name, totalRomxLen);
                                               ^~~~~~~~~~~~
src/fix/main.c:949:17: warning: format specifies type 'long' but the argument has type 'off_t' (aka 'long long') [-Wformat]
                               name, stat.st_size);
                                     ^~~~~~~~~~~~
````

**Comment by t6** [comment]
That is with 0.5.0-rc1.

**Comment by ISSOtm** [comment]
> This seems to be caused by the -D_POSIX_C_SOURCE=200809L in the Makefile. Removing it let's the build continue. Maybe the value is not quite right?

I don't see why, because [`static_assert` is part of the ISO C11 standard](https://en.cppreference.com/w/c/language/_Static_assert), and since we're setting `-std=gnu11`, we should be getting it. I don't have access to FreeBSD's headers, so I don't know what they expect. It's possible that they expect `-std=c11`? We switched to `-std=gnu11` in f88d9e728d9db5f396ac1ef2ae09af8212c37f43 to fix building in DJGPP, but maybe we ought to switch back to `c11`, and make a note that DJGPP requires changing that flag.

Worst case, you can just pass `REALCFLAGS` as a Make variable when building your package.


I am working on fixing the Clang warnings, though right now I'm only compiling for x64, and I'm seeing a lot more (`-Wall -Wextra`).

**Comment by ISSOtm** [comment]
@t6 Any news on this?

**Comment by t6** [comment]
Sorry, do you want me to retest? I see that there has been a commit about this (thanks!). Is it part of 0.5.0-rc2? I still see the same warnings with 0.5.0-rc2 now (links are IPv6 only):
http://beefy15.nyi.freebsd.org/data/130i386-default/f43705587fa6/logs/rgbds-0.5.0.r2.log
http://beefy16.nyi.freebsd.org/data/130amd64-default/f43705587fa6/logs/rgbds-0.5.0.r2.log

As for the static_assert stuff, here is what FreeBSD does
https://github.com/freebsd/freebsd-src/blob/4b45c2bb83a1d7aded0c424d65595cc576760dc7/include/assert.h#L72
https://github.com/freebsd/freebsd-src/blob/4b45c2bb83a1d7aded0c424d65595cc576760dc7/sys/sys/cdefs.h#L701
so `__ISO_C_VISIBLE` is capped to 1999 when `_POSIX_C_SOURCE=200809L` and static_assert is hidden as a result.

**Comment by ISSOtm** [comment]
I see, that's interesting. This is worth looking into whether POSIX 2008 requires ISO C99, and otherwise filing a ticket against FreeBSD's stdlib. Mixing `_POSIX_C_SOURCE=200809L` and `-std=c11` works well on at least glibc systems.

**Comment by ISSOtm** [comment]
As far as I can see, POSIX merely mentions *alignment* with the C99 standard (i.e. an intention not to conflict with it); but I don't see why `_POSIX_C_SOURCE` should override the request for C11 APIs, especially since I believe the C11 APIs in question are still POSIX 2008-conformant. Thus, I'll file a bug against FreeBSD's lib.

**Comment by t6** [comment]
Yes, I agree. Thanks for taking care of that.

**Comment by ISSOtm** [comment]
Not sure where to report, though. Moreso since I'm not a FreeBSD user myself.

**Comment by t6** [comment]
You can file bugs here: https://bugs.freebsd.org/

**Comment by t6** [comment]
Filed a bug: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255290

**Comment by ISSOtm** [comment]
Thanks, I haven't found time to do it myself yet; and your report is more detailed than what I could have provided myself ^^'

**Comment by t6** [comment]
They disagree that this is a bug and I don't know how to argue against it.

I wonder if you'd accept a patch that makes the `-D_POSIX_C_SOURCE` thing overridable. Something like
````
--- Makefile.orig       2021-04-21 18:48:01 UTC
+++ Makefile
@@ -34,8 +34,9 @@ WARNFLAGS     := -Wall

 # Overridable CFLAGS
 CFLAGS         ?= -O3 -flto -DNDEBUG
+POSIXFLAGS     := -D_POSIX_C_SOURCE=200809L
 # Non-overridable CFLAGS
-REALCFLAGS     := ${CFLAGS} ${WARNFLAGS} -std=gnu11 -D_POSIX_C_SOURCE=200809L \
+REALCFLAGS     := ${CFLAGS} ${WARNFLAGS} -std=gnu11 ${POSIXFLAGS} \
                   -Iinclude
 # Overridable LDFLAGS
 LDFLAGS                ?=
````
I can override POSIXFLAGS with `make POSIXFLAGS=` then and don't need to apply a patch. I can submit a proper PR if you want.

**Comment by ISSOtm** [comment]
POSIX only notes that it's *aligning* its definitions with C99, but does not strictly require that standard. I'm not aware of any C11 behavior conflicting with POSIX-mandated C99 behavior, and so believe that C11 + POSIX 2008 is a valid combination.

I don't think this is something that can be generalized, nor should be easy to override: RGBDS needs the POSIX 2008 APIs, if you're overriding this you need to understand the consequences on your standard library's headers.
Thus, I think it's better that, until this issue is solved one way or another, you keep patching RGBDS' Makefile for this port.

**Comment by bsdimp** [comment]
There may be a misunderstanding of its purpose. Defining this macro doesn't say you'd like the posix APIs present. It says you want only those present and no extensions defined. It defines this to be a C99 environment, though allows other environments. The trouble is, there's not a feature test macro that's defined for anything other than some open group extensions as _XOPEN_SOURCE.

The standard is silent on what to do about newer C standards presently. The ISO standards don't define anything to enable the ISO environment.

glibc defines _ISOC11_SOURCE for this purpose, but it appears to be an extension specific to glibc. neither gcc nor clang define it by default. glibc appears to only define it for _GNU_SOURCE. It uses these extensions to define __USE_ISOC11 when _ISOC11_SOURCE is set, or when the compiler is compiling for sources >= 201112. This is a bit at odds with comments in its feature.h that state:
```
   If more than one of these are defined, they accumulate.  For
   example __STRICT_ANSI__, _POSIX_SOURCE and _POSIX_C_SOURCE together
   give you ISO C, 1003.1, and 1003.2, but nothing else.
```
so even it's a bit unsure about what to do here, since it used to be quite strict about using newer things when POSIX_C_SOURCE was defined.

**Comment by bsdimp** [comment]
In the past, _POSIX_C_SOURCE has been used to specify what you want, and nothing else.

_ISOC11_SOURCE appears to be a newer extension in glibc that could solve the issue about what to do when compiling in C11 mode. glibc choses to enable this by default, but it's unclear that's standard conformant. I'll see about adding this feature test macro to FreeBSD to specify you also want isoc11 features. That would be compatible with glibc and other systems, as well as being something to fill in the gap before the open group updates posix to align it to a newer version of C.

**Comment by ISSOtm** [comment]
I read the discussion on the FreeBSD bug tracker as well as @bsdimp's [proposed change](https://reviews.freebsd.org/D29902). Since the issue seems to be out of our hands now (change to the FreeBSD headers + `make CFLAGS=-D_ISOC11_SOURCE` at the time of this writing), I'll be closing this.

Thanks again to everyone involved!

**Comment by t6** [comment]
Hold on. I can appreciate wanting to be done with it but not all of the build warnings have been addressed especially not the tautological on. I also wonder if you can't add `_ISOC11_SOURCE` on your side. It should be safe, no?

**Comment by ISSOtm** [comment]
> Hold on. I can appreciate wanting to be done with it but not all of the build warnings have been addressed especially not the tautological on.

Right, I had forgotten about the other warnings amidst all the flags discussion. See below.

> I also wonder if you can't add `_ISOC11_SOURCE` on your side. It should be safe, no?

Sure. I'll document its effect just so we're safe.

----

```
src/asm/util.c:60:30: warning: format specifies type 'unsigned char' but the argument has type 'int' [-Wformat]
                sprintf(&buf[2], "%02hhx", c);
                                  ~~~~~~   ^
                                  %02x
```

This is integer promotion shenanigans, needs fixing.

```
src/link/object.c:626:14: warning: result of comparison of constant 1152921504606846975 with expression of type 'unsigned int' is always false [-Wtautological-constant-out-of-range-compare]
        if (nbFiles > SIZE_MAX / sizeof(*nodes))
            ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is a safety check, so ensure that we can't overflow `size_t` while allocating. As it happens, `struct FileStackNode` is small enough that there's no chance for this to happen, so the warning is benign in our case.

```
src/fix/main.c:678:16: warning: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Wformat]
                       name, rom0Len);
                             ^~~~~~~
src/fix/main.c:867:10: warning: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Wformat]
                       writeLen, name, rom0Len);
                       ^~~~~~~~
src/fix/main.c:867:26: warning: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Wformat]
                       writeLen, name, rom0Len);
                                       ^~~~~~~
src/fix/main.c:879:11: warning: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Wformat]
                               writeLen, name, totalRomxLen);
                               ^~~~~~~~
src/fix/main.c:879:27: warning: format specifies type 'long' but the argument has type 'size_t' (aka 'unsigned int') [-Wformat]
                               writeLen, name, totalRomxLen);
                                               ^~~~~~~~~~~~
src/fix/main.c:949:17: warning: format specifies type 'long' but the argument has type 'off_t' (aka 'long long') [-Wformat]
                               name, stat.st_size);
                                     ^~~~~~~~~~~~
```

Ah, the joys of only compiling on x64 machines...

**Comment by ISSOtm** [comment]
#885 should have fixed those.
