### ISSUE TITLE
rgbasm: src/asm/symbol.c:533: sym_AddLocalLabel: Assertion `strchr(&name[i], '.')' failed.

### ISSUE THREAD

**Issue by NieDzejkob** [gbdev/rgbds#832]
```
SECTION "Test", ROM0
F:
a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.
```

**Comment by ISSOtm** [comment]
The assertion checks that a local label's name contains at least one dot... but since the label name is larger than the symbol name buffer, the dot gets discarded.

Fixing this should be as simple as moving this into the `if (i < sizeof(yylval.tzSym) - 1)` block.
https://github.com/gbdev/rgbds/blob/215e26b478c1cbf5a5d5dd86e7ee027072acaaac/src/asm/lexer.c#L1237-L1239
