### ISSUE TITLE
[Feature request] Hexadecimal fixed-point literals

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#840]
For instance, `$2a.8 == 42.5`. I think this would be worthwhile for fixed-point values that are evenly divide into powers of 2, but have to be rounded off to "near-enough" decimals.

These would be simpler to format than decimal fixed-point, since the fractional part would always have maximum 4 digits and then just trailing zeros.

**Comment by ISSOtm** [comment]
Is there much benefit to `$2A.8` over `$2A8000`?

**Comment by Rangi42** [comment]
Arguably makes the intention clearer, although `$2a_8000` isn't too bad.

**Comment by ISSOtm** [comment]
Yeah, I'd rather go with that one. I'm not too fond of the existing fixed-point support, personally, because there's no way to specify the fixed-point width. (I use 12.4, so I don't get any support; 16.8 would also make sense, but same problem. User-defined functions could probably deal with that, maybe... but I don't see how we could have literals support that.)
