### ISSUE TITLE
[Feature request] Either make STRCMP use the charmap values or add CHARCMP

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#854]
Usually I see `STRCMP` called to test string equality, for which it doesn't matter whether the charmap is used or not. However, I expect that when strings are being ordered, their in-game charmapped values are what matter, not UTF-8.

Here's one instance: [slist.asm](https://pastebin.com/r9KsyLMa) implements macros for lists of strings. `slist_sort` sorts a list. Presumably the lists are meant to eventually go in a ROM, so for that purpose they should be sorted according to the charmap.

**Comment by ISSOtm** [comment]
You can now iterate on all the charmap entries, and compare the converted values one by one.

**Comment by aaaaaa123456789** [comment]
As long as you guys keep fixating on using the same syntax for strings and characters, which I honestly don't know why you insist on, this will always look weird. `"ab" > "cd"` could be anything, ranging from a numerical comparison to a string comparison to... a string compared to a number? Because maybe _one_ of them is a number and the other one isn't?
And then we're in this weird JavaScript-like limbo where `"ab" > "cd"` makes sense, `"cd" > 0` makes sense, but `"ab" > 0` doesn't work at all (because there's a charmap entry for `"cd"`, but not `"ab"`), which breaks transitivity in the weirdest of ways?

The fact that quoted literals are a bit too typefluid makes consistency a big problem. I honestly don't think this is as unambiguous as it might seem.

**Comment by aaaaaa123456789** [comment]
I'd say that most people would expect simple relationships (e.g., `a > b` and `b > c` implying `a > c`, or `a == b` and `b != c` implying `a != c`) to hold. This kind of thing breaks that, because now `b` means different things in different contexts.

Don't get me wrong: this happens in other languages. In C, for instance, you get `1u > 0`, `0 > -1` and `-1 > 1u`. But this is not what you want, for the most part.

**Comment by aaaaaa123456789** [comment]
> Unless "`"foo"` and `num` might be incomparable" is what you consider a different context, though.

This is kind of what I meant. In one context, `"bar"` is a string. In the other context, it is coerced to a number, a completely different class of data. `"foo"` has no numeric coercion.
