### ISSUE TITLE
src/asm/lexer.c unnecessarily includes extern/utf8decoder.h

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#937]
extern/utf8decoder.h only declares a `decode` function, and that's only used in src/asm/parser.y and src/asm/util.c (by `readUTF8Char`, which is only called in src/asm/charmap.c).

**Comment by Rangi42** [comment]
(More generally, let's look for any other unused `#include`s.)

**Comment by ISSOtm** [comment]
I'm pretty sure it's a holdover from when the lexer warned about invalid UTF-8 codepoints, instead of just warning about the bytes like it does now. No harm in fixing includes, though. Ideally we'd also fix "transitive" headers, but that sounds too daunting a task vs. the gain to be worth fixing \*shrug\*.
