### ISSUE TITLE
[Bug] Binary literals can use `_` as a custom character

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#950]
`_` is allowed as a digit separator in `decimal`, `$hex`, `&octal`, and `%binary` literals. It's not allowed in `` `gfx`` literals because `opt g` might have assigned `_` as one of the four digit characters. However, `opt b` might also have assigned `_` as a binary digit character.

Should we disallow `_` from being a custom digit character, and then allow it as a separator for gfx literals too?

**Comment by ISSOtm** [comment]
I don't think the current behavior is a bug; if you want `_` to be meaningful in those literals, it makes sense to let it be. Then, the behavior should be that `_` is treated as a digit if specified as such, and otherwise as a separator.

The potential inconsistency that it creates is `_` being treated differently in e.g. macros depending on outer context, but I see no sane use case that would depend on this.

**Comment by Rangi42** [comment]
In that case maybe `` `gfx` should allow it too.
