### ISSUE TITLE
[Feature request] numeric escape sequences in strings

### ISSUE THREAD

**Issue by JL2210** [gbdev/rgbds#962]
Numeric escape sequences in strings such as e.g. `\000` `\xff` (in particular, the former) might be useful for automatic code generators so that they don't have to output an additional zero outside of the string.

Example:

```
  db "Hello, World!\x00"
```

**Comment by Rangi42** [comment]
You can do `charmap "$x00", 0` and then `db "Hello, World!$x00"`. This avoids storing arbitrary bytes in strings during rgbasm processing (so they stay as valid UTF-8 encoding), and only does the charmap-to-byte conversion when inserting bytes into the ROM.

Actually storing arbitrary bytes in strings is a matter for #938.

**Comment by aaaaaa123456789** [comment]
Octal strings are impossible to add: `\1`, `\2`, and so on are macro expansions.

That being said, there's a bigger underlying problem here: the source character set doesn't match the output character set. The existence of `charmap` means that you cannot be sure that `db "abc"` will be equivalent to `db $61, $62, $63` unless you control the full source of the translation unit. Automatic code generators often cannot make that assumption in the first place.

And if you control the full source of the translation unit, you can define your own escape sequences (perhaps in an included file) and just use them anywhere. Backslashes aren't available, but you can use literally any other character:

```
  charmap "``", $60 ; first of all, have the backtick escape itself
  charmap "`n", $0a
  charmap "`t", $09
  charmap "`x00", $00
  charmap "`x01", $01
  ; ...and so on
```

**Comment by Rangi42** [comment]
That can even be automated:

```
	charmap "``", $60
	for n, 256
		charmap "`x{02x:n}", n
	endr
```

**Comment by ISSOtm** [comment]
Should this be closed, then?
