### ISSUE TITLE
Revise the `make develop` warning flags

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#969]
`make develop` specifies these warning flags but doesn't need to:

- `-Wformat` (enabled by `-Wall`)
- `-Wformat-truncation=1` (enabled by `-Wformat`)
- `-Wuninitialized` (enabled by `-Wall`)
- `-Wunknown-pragmas` (enabled by `-Wall`)

It does not use these warning flags, which are not enabled even by `-Wall -Wextra -pedantic` and may be useful:

- `-Wc++-compat` (this prints a lot of warnings, many related to implicit conversion from `void *`)
- `-Wconversion` (this prints a lot of warnings, which may be false positives)
- `-Wduplicated-branches`
- `-Wnull-dereference`
- `-Wshift-overflow=2`
- `-Wtrampolines`
- `-Wunused-macros` (this would be useful for our own code, but it prints spurious warnings for bison-generated parser.c; the Makefile could have its own rule for parser.o instead of the standard `.c.o` one, to omit `-Wunused-macros` from it)
- `-Wwrite-strings` (this enables `-Wdiscarded-qualifiers`, which prints some warnings for assigning string literals, which are `const char *`, to `char *` variables in rgbgfx; it might be appropriate to make those variables `const`)

**Comment by ISSOtm** [comment]
Since we're tackling this, we should also take care of #283.

**Comment by ISSOtm** [comment]
- I haven't enabled `-Wc++-compat` because we're not attempting to move to C++ *yet*.
- Our coding style relies on implicit conversions too much for `-Wconversion` to be useful *right now*.
- `-Wnull-dereference`, as well as `-Wstringop-overflow`, don't do much without optimizations; I set the optimization level to `-Og`, but that let GCC find an error in `src/gfx/makepng.c` (augh! When's RGBGFX getting the axe or a rewrite!?)
- Not sure `-Wshift-overflow=2` is really useful if we are planning to switch to C++14+, as it's a no-op there.
- We're not concerned with `-Wtrampolines` because we don't use nested functions anyway.
- `-Wunused-macros` complains about the unused `tryFgetc`, though I'd prefer keeping it in case we need to read individual bytes later.
- `-Wwrite-strings` complains *massively* in RGBGFX (...); there were a couple of mistakes in RGBASM, but I fixed those.

**Comment by Rangi42** [comment]
I agree with your points except for not adding `-Wunused-macros`. The definition of `tryFgetc` is trivial to rewrite if we ever need it, or it can just be commented out for now. And actually we'd probably never need it, since the [only difference](https://stackoverflow.com/questions/18480982/getc-vs-fgetc-what-are-the-major-differences) is that `fgetc` is always a function whereas `getc` might be a macro.
